class LanguageManager:
    """多语言管理器 - 管理当前语言并提供文案翻译。"""

    DEFAULT_LANGUAGE = "en-US"
    SUPPORTED_LANGUAGES = ("en-US", "zh-CN")

    TRANSLATIONS = {
        "en-US": {
            "menu.title": "VisionSeed",
            "menu.subtitle": "Visual Training System",
            "menu.start_training": "Start Training",
            "menu.configuration": "Configuration",
            "menu.view_history": "View History",
            "menu.exit": "Exit",
            "menu.hint": "Shortcuts: 1-4  Esc closes current screen",
            "license.title": "License Activation",
            "license.subtitle": "Send your device hash to seller for a device-bound token",
            "license.device_hash": "Device Hash",
            "license.copy_hash": "Copy Hash",
            "license.input_placeholder": "Paste activation token (VS1....)",
            "license.activate": "Activate",
            "license.exit": "Exit",
            "license.hint": "C: Copy Hash  Enter: Activate  Esc: Exit",
            "license.success": "Activation succeeded.",
            "license.copy_success": "Device hash copied.",
            "license.copy_failed": "Copy failed. Please copy manually.",
            "license.paste_success": "Token pasted.",
            "license.paste_failed": "Paste failed. Please input manually.",
            "license.error_empty": "Please paste activation token.",
            "license.error_invalid": "Activation failed",
            "config.title": "Game Configuration",
            "config.info": "Click to configure  Enter: Start  Esc: Back",
            "config.difficulty_level": "Difficulty Level",
            "config.font_preview": "Font Size Preview",
            "config.question_count": "Question Count",
            "config.range": "Range: {min_questions}-{max_questions}",
            "config.status": "Current: Level {level} ({size}px), Questions: {questions}",
            "config.section_preferences": "Preferences",
            "config.adjust_hint": "Use +/- or type value",
            "config.preview_level_size": "Level L{level}  Size {size}px",
            "config.preview_hover_tip": "Hovering L{level}: click to apply",
            "config.preview_recommend": "Suggested distance: {distance} m",
            "config.input_error_digits": "Please enter digits only",
            "config.input_error_range": "Range must be {min_questions}-{max_questions}",
            "config.input_error_empty": "Question count cannot be empty",
            "config.sound_label": "Sound",
            "config.lang_label": "Language",
            "config.on": "ON",
            "config.off": "OFF",
            "config.sound_on": "Sound: ON (M)",
            "config.sound_off": "Sound: OFF (M)",
            "config.language": "Language: {language} (L)",
            "config.start_game": "Start Game",
            "config.back": "Back",
            "config.lang_en": "English",
            "config.lang_zh": "Chinese",
            "report.title": "Training Report",
            "report.total_questions": "Total Questions: {total}",
            "report.correct": "Correct: {correct}",
            "report.wrong": "Wrong: {wrong}",
            "report.accuracy": "Accuracy: {accuracy}%",
            "report.time_used": "Time Used: {duration} s",
            "report.max_combo": "Max Combo: {combo}",
            "report.return_hint": "Enter: Retry  Esc: Menu",
            "report.retry": "Retry",
            "report.back_menu": "Back to Menu",
            "report.result_excellent": "Excellent",
            "report.result_good": "Good Progress",
            "report.result_keep_going": "Keep Going",
            "report.trend_accuracy": "Accuracy vs last: {delta}% {arrow}",
            "report.trend_duration": "Time vs last: {delta}s {arrow}",
            "report.trend_no_history": "Complete one more session to see trends.",
            "report.suggestion_raise": "Suggestion: try a harder level (L{level}) next time.",
            "report.suggestion_keep": "Suggestion: keep current Level {level}.",
            "report.suggestion_lower": "Suggestion: try an easier level (L{level}) to stabilize.",
            "training.back": "Back",
            "training.combo": "Combo x{combo}",
            "training.max_combo": "Max Combo: {combo}",
            "history.title": "Training History",
            "history.info_with_records": "Left/Right: Navigate  R: Refresh  ESC/Back: Return",
            "history.info_empty": "No records. Press R to refresh, ESC/Back to return.",
            "history.header.datetime": "Date & Time",
            "history.header.level": "Level",
            "history.header.questions": "Questions",
            "history.header.correct": "Correct",
            "history.header.accuracy": "Accuracy",
            "history.header.duration": "Duration",
            "history.invalid_date": "Invalid Date",
            "history.page_info": "Page {current} of {total}",
            "history.back": "Back",
            "history.filter.date": "Date",
            "history.filter.level": "Level",
            "history.filter.sort": "Sort",
            "history.filter.all": "All",
            "history.filter.7d": "7D",
            "history.filter.30d": "30D",
            "history.sort.time": "Time",
            "history.sort.accuracy": "Accuracy",
        },
        "zh-CN": {
            "menu.title": "视芽",
            "menu.subtitle": "视觉训练系统",
            "menu.start_training": "开始训练",
            "menu.configuration": "参数配置",
            "menu.view_history": "训练历史",
            "menu.exit": "退出",
            "menu.hint": "快捷键：1-4  Esc 关闭当前界面",
            "license.title": "授权激活",
            "license.subtitle": "请将设备哈希发给卖家，获取绑定本机的授权码",
            "license.device_hash": "设备哈希",
            "license.copy_hash": "复制哈希",
            "license.input_placeholder": "请粘贴授权码（VS1....）",
            "license.activate": "激活",
            "license.exit": "退出",
            "license.hint": "C: 复制哈希  回车: 激活  Esc: 退出",
            "license.success": "激活成功。",
            "license.copy_success": "设备哈希已复制。",
            "license.copy_failed": "复制失败，请手动抄录。",
            "license.paste_success": "授权码已粘贴。",
            "license.paste_failed": "粘贴失败，请手动输入。",
            "license.error_empty": "请先输入授权码。",
            "license.error_invalid": "激活失败",
            "config.title": "训练配置",
            "config.info": "点击进行配置  回车: 开始  ESC: 返回",
            "config.difficulty_level": "难度等级",
            "config.font_preview": "字号预览",
            "config.question_count": "题目数量",
            "config.range": "范围: {min_questions}-{max_questions}",
            "config.status": "当前: 等级 {level} ({size}px), 题数: {questions}",
            "config.section_preferences": "偏好设置",
            "config.adjust_hint": "可使用 +/- 或直接输入",
            "config.preview_level_size": "等级 L{level}  尺寸 {size}px",
            "config.preview_hover_tip": "悬停 L{level}：点击即可应用",
            "config.preview_recommend": "建议训练距离：{distance} 米",
            "config.input_error_digits": "请输入数字",
            "config.input_error_range": "范围必须在 {min_questions}-{max_questions}",
            "config.input_error_empty": "题目数量不能为空",
            "config.sound_label": "音效",
            "config.lang_label": "语言",
            "config.on": "开",
            "config.off": "关",
            "config.sound_on": "音效: 开 (M)",
            "config.sound_off": "音效: 关 (M)",
            "config.language": "语言: {language} (L)",
            "config.start_game": "开始训练",
            "config.back": "返回",
            "config.lang_en": "英文",
            "config.lang_zh": "中文",
            "report.title": "训练报告",
            "report.total_questions": "总题数: {total}",
            "report.correct": "正确: {correct}",
            "report.wrong": "错误: {wrong}",
            "report.accuracy": "正确率: {accuracy}%",
            "report.time_used": "用时: {duration} 秒",
            "report.max_combo": "最高连击：{combo}",
            "report.return_hint": "回车: 再来一组  Esc: 返回菜单",
            "report.retry": "再来一组",
            "report.back_menu": "返回菜单",
            "report.result_excellent": "表现优秀",
            "report.result_good": "进步明显",
            "report.result_keep_going": "继续加油",
            "report.trend_accuracy": "较上次正确率: {delta}% {arrow}",
            "report.trend_duration": "较上次用时: {delta}秒 {arrow}",
            "report.trend_no_history": "再完成一次训练后可查看趋势。",
            "report.suggestion_raise": "建议：下次尝试更高难度（L{level}）。",
            "report.suggestion_keep": "建议：保持当前等级 {level}。",
            "report.suggestion_lower": "建议：尝试更低难度（L{level}）以稳定训练。",
            "training.back": "返回",
            "training.combo": "连击 x{combo}",
            "training.max_combo": "最高连击：{combo}",
            "history.title": "训练历史",
            "history.info_with_records": "左右键: 翻页  R: 刷新  ESC/返回: 回菜单",
            "history.info_empty": "暂无记录。按 R 刷新，ESC/返回 回菜单。",
            "history.header.datetime": "日期时间",
            "history.header.level": "等级",
            "history.header.questions": "题数",
            "history.header.correct": "正确",
            "history.header.accuracy": "正确率",
            "history.header.duration": "用时",
            "history.invalid_date": "无效日期",
            "history.page_info": "第 {current}/{total} 页",
            "history.back": "返回",
            "history.filter.date": "时间",
            "history.filter.level": "等级",
            "history.filter.sort": "排序",
            "history.filter.all": "全部",
            "history.filter.7d": "7天",
            "history.filter.30d": "30天",
            "history.sort.time": "时间",
            "history.sort.accuracy": "正确率",
        },
    }

    def __init__(self, language=DEFAULT_LANGUAGE):
        self.current_language = self.DEFAULT_LANGUAGE
        self.set_language(language)

    def set_language(self, language):
        if language in self.SUPPORTED_LANGUAGES:
            self.current_language = language
        else:
            self.current_language = self.DEFAULT_LANGUAGE
        return self.current_language

    def cycle_language(self):
        if self.current_language == "en-US":
            self.current_language = "zh-CN"
        else:
            self.current_language = "en-US"
        return self.current_language

    def get_language(self):
        return self.current_language

    def t(self, key, **kwargs):
        language_map = self.TRANSLATIONS.get(self.current_language, {})
        fallback_map = self.TRANSLATIONS[self.DEFAULT_LANGUAGE]
        template = language_map.get(key, fallback_map.get(key, key))
        if kwargs:
            try:
                return template.format(**kwargs)
            except (KeyError, ValueError):
                return template
        return template
