class LanguageManager:
    """多语言管理器 - 管理当前语言并提供文案翻译。"""

    DEFAULT_LANGUAGE = "en-US"
    SUPPORTED_LANGUAGES = ("en-US", "zh-CN")

    TRANSLATIONS = {
        "en-US": {
            "menu.title": "VisionSeed",
            "menu.subtitle": "Visual Training System",
            "menu.start_training": "Start Training",
            "menu.configuration": "Configuration",
            "menu.view_history": "View History",
            "menu.exit": "Exit",
            "menu.hint": "Shortcuts: 1-7  Esc closes current screen",
            "menu.template_title": "Quick Plans",
            "menu.template_child": "Child Plan",
            "menu.template_adult": "Adult Plan",
            "menu.template_recovery": "Recovery Plan",
            "onboarding.title": "30s Quick Start",
            "onboarding.subtitle": "Finish this once before your first training session",
            "onboarding.tip1": "Sit upright, keep a stable viewing distance, and avoid glare.",
            "onboarding.tip2": "Use arrow keys to answer E direction (Up/Down/Left/Right).",
            "onboarding.tip3": "Train 5-10 minutes per session, 1-2 sessions per day.",
            "onboarding.tip4": "This app is a training aid, not a medical diagnosis/treatment.",
            "onboarding.estimate": "Recommended start: L4 / 20-30 questions / steady pace",
            "onboarding.start": "I Understand",
            "onboarding.skip": "Skip",
            "license.title": "License Activation",
            "license.subtitle": "Send your device hash to seller for a device-bound token",
            "license.device_hash": "Device Hash",
            "license.copy_hash": "Copy Hash",
            "license.paste": "Paste",
            "license.paste_tip": "Tip: click Paste or press Ctrl+V",
            "license.input_placeholder": "Paste activation token (VS1....)",
            "license.activate": "Activate",
            "license.exit": "Exit",
            "license.hint": "C: Copy Hash  Enter: Activate  Esc: Exit",
            "license.success": "Activation succeeded.",
            "license.copy_success": "Device hash copied.",
            "license.copy_failed": "Copy failed. Please copy manually.",
            "license.paste_success": "Token pasted.",
            "license.paste_failed": "Paste failed. Please input manually.",
            "license.error_empty": "Please paste activation token.",
            "license.error_invalid": "Activation failed",
            "license.err.ERR_FORMAT": "Token format is invalid.",
            "license.err.ERR_PREFIX": "Token prefix is invalid.",
            "license.err.ERR_PAYLOAD": "Token payload is corrupted.",
            "license.err.ERR_SIGNATURE": "Token signature check failed.",
            "license.err.ERR_STATUS": "License status is not active.",
            "license.err.ERR_SCHEMA": "License version is unsupported.",
            "license.err.ERR_DEVICE": "This token does not match this device.",
            "license.err.ERR_EXPIRED": "License has expired.",
            "license.err.ERR_WRITE": "Local license file write failed.",
            "license.err.ERR_NOT_FOUND": "License file not found.",
            "license.err.ERR_UNREADABLE": "License file is unreadable.",
            "license.err.OK": "OK",
            "config.title": "Game Configuration",
            "config.info": "Enter: Start  Ctrl+S: Save&Back  Esc: Cancel  A: Adaptive",
            "config.difficulty_level": "Difficulty Level",
            "config.font_preview": "Font Size Preview",
            "config.question_count": "Question Count",
            "config.range": "Range: {min_questions}-{max_questions}",
            "config.status": "Current: Level {level} ({size}px), Questions: {questions}",
            "config.section_preferences": "Preferences",
            "config.adjust_hint": "Use +/- or type value",
            "config.preview_level_size": "Level L{level}  Size {size}px",
            "config.preview_hover_tip": "Hovering L{level}: click to apply",
            "config.preview_recommend": "Suggested distance: {distance} m",
            "config.group_challenge": "Challenge",
            "config.group_standard": "Standard",
            "config.group_entry": "Entry",
            "config.input_error_digits": "Please enter digits only",
            "config.input_error_range": "Range must be {min_questions}-{max_questions}",
            "config.input_error_empty": "Question count cannot be empty",
            "config.feedback_saved": "Settings saved.",
            "config.feedback_canceled": "Changes canceled.",
            "config.sound_label": "Sound",
            "config.lang_label": "Language",
            "config.adaptive_label": "Adaptive Difficulty (A)",
            "config.on": "ON",
            "config.off": "OFF",
            "config.sound_on": "Sound: ON (M)",
            "config.sound_off": "Sound: OFF (M)",
            "config.language": "Language: {language} (L)",
            "config.start_game": "Start Game",
            "config.back": "Back",
            "config.save_back": "Save & Back",
            "config.cancel": "Cancel",
            "config.adaptive_desc_short": "Adaptive difficulty auto-adjusts next level.",
            "config.adaptive_desc": "Adaptive difficulty auto-adjusts next level based on your recent 3 sessions (accuracy/time).",
            "config.lang_en": "English",
            "config.lang_zh": "Chinese",
            "report.title": "Training Report",
            "report.total_questions": "Total Questions: {total}",
            "report.correct": "Correct: {correct}",
            "report.wrong": "Wrong: {wrong}",
            "report.accuracy": "Accuracy: {accuracy}%",
            "report.time_used": "Time Used: {duration} s",
            "report.max_combo": "Max Combo: {combo}",
            "report.return_hint": "Enter: Retry  Esc: Menu",
            "report.retry": "Retry",
            "report.back_menu": "Back to Menu",
            "report.result_excellent": "Excellent",
            "report.result_good": "Good Progress",
            "report.result_keep_going": "Keep Going",
            "report.trend_accuracy": "Accuracy vs last: {delta}% {arrow}",
            "report.trend_duration": "Time vs last: {delta}s {arrow}",
            "report.trend_no_history": "Complete one more session to see trends.",
            "report.suggestion_raise": "Suggestion: try a harder level (L{level}) next time.",
            "report.suggestion_keep": "Suggestion: keep current Level {level}.",
            "report.suggestion_lower": "Suggestion: try an easier level (L{level}) to stabilize.",
            "report.next_plan": "Next: L{level}, {questions} questions, about {minutes} min",
            "report.adaptive_up": "Adaptive: L{old} -> L{new} (avg3 acc {acc}%, {sec}s/question)",
            "report.adaptive_down": "Adaptive: L{old} -> L{new} (avg3 acc {acc}%, {sec}s/question)",
            "report.adaptive_keep": "Adaptive: keep L{level} (avg3 acc {acc}%, {sec}s/question)",
            "report.adaptive_cooldown": "Adaptive cooldown: {cooldown} session(s) left, keep L{level}",
            "report.adaptive_insufficient": "Adaptive pending: need 3 valid sessions.",
            "report.adaptive_disabled": "Adaptive difficulty is OFF.",
            "training.back": "Back",
            "training.combo": "Combo x{combo}",
            "training.max_combo": "Max Combo: {combo}",
            "training.pause": "Pause",
            "training.resume": "Resume",
            "training.paused": "Paused",
            "training.pause_hint": "P: Pause/Resume",
            "training.completed": "Training complete. Preparing report...",
            "training.skip_hint": "Press Enter to continue now",
            "history.title": "Training History",
            "history.info_with_records": "Left/Right: Navigate  R: Refresh  ESC/Back: Return",
            "history.info_empty": "No records. Press R to refresh, ESC/Back to return.",
            "history.header.datetime": "Date & Time",
            "history.header.level": "Level",
            "history.header.questions": "Questions",
            "history.header.correct": "Correct",
            "history.header.accuracy": "Accuracy",
            "history.header.duration": "Duration",
            "history.invalid_date": "Invalid Date",
            "history.page_info": "Page {current} of {total}",
            "history.back": "Back",
            "history.filter.date": "Date",
            "history.filter.level": "Level",
            "history.filter.sort": "Sort",
            "history.filter.all": "All",
            "history.filter.7d": "7D",
            "history.filter.30d": "30D",
            "history.sort.time": "Time",
            "history.sort.accuracy": "Accuracy",
        },
        "zh-CN": {
            "menu.title": "视芽",
            "menu.subtitle": "视觉训练系统",
            "menu.start_training": "开始训练",
            "menu.configuration": "参数配置",
            "menu.view_history": "训练历史",
            "menu.exit": "退出",
            "menu.hint": "快捷键：1-7  Esc 关闭当前界面",
            "menu.template_title": "快捷训练方案",
            "menu.template_child": "儿童方案",
            "menu.template_adult": "成人方案",
            "menu.template_recovery": "恢复方案",
            "onboarding.title": "30秒快速上手",
            "onboarding.subtitle": "首次使用建议先完成一次引导",
            "onboarding.tip1": "坐姿端正，保持稳定训练距离，避免环境眩光。",
            "onboarding.tip2": "使用方向键判断 E 方向（上/下/左/右）。",
            "onboarding.tip3": "每次训练 5-10 分钟，每日 1-2 次。",
            "onboarding.tip4": "本软件为训练辅助工具，不替代医疗诊断与治疗。",
            "onboarding.estimate": "建议起步：L4 / 20-30题 / 匀速完成",
            "onboarding.start": "我已了解",
            "onboarding.skip": "跳过",
            "license.title": "授权激活",
            "license.subtitle": "请将设备哈希发给卖家，获取绑定本机的授权码",
            "license.device_hash": "设备哈希",
            "license.copy_hash": "复制哈希",
            "license.paste": "粘贴",
            "license.paste_tip": "提示：可点“粘贴”或按 Ctrl+V",
            "license.input_placeholder": "请粘贴授权码（VS1....）",
            "license.activate": "激活",
            "license.exit": "退出",
            "license.hint": "C: 复制哈希  回车: 激活  Esc: 退出",
            "license.success": "激活成功。",
            "license.copy_success": "设备哈希已复制。",
            "license.copy_failed": "复制失败，请手动抄录。",
            "license.paste_success": "授权码已粘贴。",
            "license.paste_failed": "粘贴失败，请手动输入。",
            "license.error_empty": "请先输入授权码。",
            "license.error_invalid": "激活失败",
            "license.err.ERR_FORMAT": "授权码格式错误。",
            "license.err.ERR_PREFIX": "授权码前缀无效。",
            "license.err.ERR_PAYLOAD": "授权码内容损坏。",
            "license.err.ERR_SIGNATURE": "授权码签名校验失败。",
            "license.err.ERR_STATUS": "授权状态不是可用状态。",
            "license.err.ERR_SCHEMA": "授权版本不受支持。",
            "license.err.ERR_DEVICE": "授权码与当前设备不匹配。",
            "license.err.ERR_EXPIRED": "授权已过期。",
            "license.err.ERR_WRITE": "本地授权文件写入失败。",
            "license.err.ERR_NOT_FOUND": "未找到本地授权文件。",
            "license.err.ERR_UNREADABLE": "本地授权文件损坏。",
            "license.err.OK": "正常",
            "config.title": "训练配置",
            "config.info": "回车: 开始  Ctrl+S: 保存返回  ESC: 取消  A: 自适应",
            "config.difficulty_level": "难度等级",
            "config.font_preview": "字号预览",
            "config.question_count": "题目数量",
            "config.range": "范围: {min_questions}-{max_questions}",
            "config.status": "当前: 等级 {level} ({size}px), 题数: {questions}",
            "config.section_preferences": "偏好设置",
            "config.adjust_hint": "可使用 +/- 或直接输入",
            "config.preview_level_size": "等级 L{level}  尺寸 {size}px",
            "config.preview_hover_tip": "悬停 L{level}：点击即可应用",
            "config.preview_recommend": "建议训练距离：{distance} 米",
            "config.group_challenge": "挑战区",
            "config.group_standard": "标准区",
            "config.group_entry": "入门区",
            "config.input_error_digits": "请输入数字",
            "config.input_error_range": "范围必须在 {min_questions}-{max_questions}",
            "config.input_error_empty": "题目数量不能为空",
            "config.feedback_saved": "设置已保存。",
            "config.feedback_canceled": "已取消本次修改。",
            "config.sound_label": "音效",
            "config.lang_label": "语言",
            "config.adaptive_label": "自适应难度 (A)",
            "config.on": "开",
            "config.off": "关",
            "config.sound_on": "音效: 开 (M)",
            "config.sound_off": "音效: 关 (M)",
            "config.language": "语言: {language} (L)",
            "config.start_game": "开始训练",
            "config.back": "返回",
            "config.save_back": "保存返回",
            "config.cancel": "取消",
            "config.adaptive_desc_short": "自适应难度会自动调节下次等级。",
            "config.adaptive_desc": "自适应难度，会根据最近3次训练（正确率/用时），自动调节下次的等级难度。",
            "config.lang_en": "英文",
            "config.lang_zh": "中文",
            "report.title": "训练报告",
            "report.total_questions": "总题数: {total}",
            "report.correct": "正确: {correct}",
            "report.wrong": "错误: {wrong}",
            "report.accuracy": "正确率: {accuracy}%",
            "report.time_used": "用时: {duration} 秒",
            "report.max_combo": "最高连击：{combo}",
            "report.return_hint": "回车: 再来一组  Esc: 返回菜单",
            "report.retry": "再来一组",
            "report.back_menu": "返回菜单",
            "report.result_excellent": "表现优秀",
            "report.result_good": "进步明显",
            "report.result_keep_going": "继续加油",
            "report.trend_accuracy": "较上次正确率: {delta}% {arrow}",
            "report.trend_duration": "较上次用时: {delta}秒 {arrow}",
            "report.trend_no_history": "再完成一次训练后可查看趋势。",
            "report.suggestion_raise": "建议：下次尝试更高难度（L{level}）。",
            "report.suggestion_keep": "建议：保持当前等级 {level}。",
            "report.suggestion_lower": "建议：尝试更低难度（L{level}）以稳定训练。",
            "report.next_plan": "下次建议：L{level}，{questions}题，约 {minutes} 分钟",
            "report.adaptive_up": "自适应：L{old} -> L{new}（近3次正确率 {acc}% ，{sec}秒/题）",
            "report.adaptive_down": "自适应：L{old} -> L{new}（近3次正确率 {acc}% ，{sec}秒/题）",
            "report.adaptive_keep": "自适应：保持 L{level}（近3次正确率 {acc}% ，{sec}秒/题）",
            "report.adaptive_cooldown": "自适应冷却中：剩余 {cooldown} 次，保持 L{level}",
            "report.adaptive_insufficient": "自适应等待中：至少需要3次有效训练记录。",
            "report.adaptive_disabled": "自适应难度已关闭。",
            "training.back": "返回",
            "training.combo": "连击 x{combo}",
            "training.max_combo": "最高连击：{combo}",
            "training.pause": "暂停",
            "training.resume": "继续",
            "training.paused": "已暂停",
            "training.pause_hint": "P：暂停/继续",
            "training.completed": "训练完成，正在生成报告...",
            "training.skip_hint": "按回车可立即继续",
            "history.title": "训练历史",
            "history.info_with_records": "左右键: 翻页  R: 刷新  ESC/返回: 回菜单",
            "history.info_empty": "暂无记录。按 R 刷新，ESC/返回 回菜单。",
            "history.header.datetime": "日期时间",
            "history.header.level": "等级",
            "history.header.questions": "题数",
            "history.header.correct": "正确",
            "history.header.accuracy": "正确率",
            "history.header.duration": "用时",
            "history.invalid_date": "无效日期",
            "history.page_info": "第 {current}/{total} 页",
            "history.back": "返回",
            "history.filter.date": "时间",
            "history.filter.level": "等级",
            "history.filter.sort": "排序",
            "history.filter.all": "全部",
            "history.filter.7d": "7天",
            "history.filter.30d": "30天",
            "history.sort.time": "时间",
            "history.sort.accuracy": "正确率",
        },
    }

    def __init__(self, language=DEFAULT_LANGUAGE):
        self.current_language = self.DEFAULT_LANGUAGE
        self.set_language(language)

    def set_language(self, language):
        if language in self.SUPPORTED_LANGUAGES:
            self.current_language = language
        else:
            self.current_language = self.DEFAULT_LANGUAGE
        return self.current_language

    def cycle_language(self):
        if self.current_language == "en-US":
            self.current_language = "zh-CN"
        else:
            self.current_language = "en-US"
        return self.current_language

    def get_language(self):
        return self.current_language

    def t(self, key, **kwargs):
        language_map = self.TRANSLATIONS.get(self.current_language, {})
        fallback_map = self.TRANSLATIONS[self.DEFAULT_LANGUAGE]
        template = language_map.get(key, fallback_map.get(key, key))
        if kwargs:
            try:
                return template.format(**kwargs)
            except (KeyError, ValueError):
                return template
        return template
