from .eye_find_patterns.game import build_descriptor as build_eye_find_patterns_descriptor
from .pong.game import build_descriptor as build_pong_descriptor
from .spot_difference import build_descriptor as build_spot_difference_descriptor
